(() => {
'use strict';
const $=id=>document.getElementById(id);
let tvEnabled=false,currentFocus=null;
const MODE_KEY='cineflex_tv_mode';
const TV_UA=/(android tv|google tv|smart-tv|smarttv|hbbtv|netcast|web0s|webos|tizen|viera|bravia|aftb|aftm|aftt|fire tv|roku|crkey|chromecast)/i;
const focusSelector='button:not([disabled]),a[href],[tabindex="0"],.drawer-item,.card,.movie-card,.dramabox-card,.netflix-item-container,.search-card,.cf-smart-card,.cf-top10-card,.cf51-because-card,.cf-catalog-card,.similar-card,.episode-card,.profile-card,.server-btn,.modern-grid-item';

function visible(e){if(!e||!e.isConnected)return false;const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity||1)>.05&&r.width>5&&r.height>5}
function scope(){const layers=[...document.querySelectorAll('.modal,.search-overlay,.menu-drawer,[role="dialog"]')].reverse();return layers.find(e=>visible(e)&&(e.classList.contains('open')||e.classList.contains('active')||getComputedStyle(e).display!=='none'))||document}
function candidates(){return [...scope().querySelectorAll(focusSelector)].filter(visible)}
function center(e){const r=e.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2,h:r.height,w:r.width}}
function setFocus(e,scroll=true){if(!e||!visible(e))return;document.querySelectorAll('.cf304-focus').forEach(x=>x.classList.remove('cf304-focus'));currentFocus=e;e.classList.add('cf304-focus');if(!e.hasAttribute('tabindex')&&!/^(BUTTON|A|INPUT|SELECT|TEXTAREA)$/.test(e.tagName))e.tabIndex=0;try{e.focus({preventScroll:true})}catch{try{e.focus()}catch{}}if(scroll)e.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}
function firstFocus(){const all=candidates();setFocus(all.find(e=>e.classList.contains('play-btn')||e.id==='banner-play-btn')||all[0],false)}
function move(dir){const all=candidates();if(!all.length)return;if(!currentFocus||!all.includes(currentFocus)||!visible(currentFocus)){firstFocus();return}const a=center(currentFocus);let best=null,score=Infinity;for(const e of all){if(e===currentFocus)continue;const b=center(e),dx=b.x-a.x,dy=b.y-a.y;const primary=dir==='left'?-dx:dir==='right'?dx:dir==='up'?-dy:dy;if(primary<=6)continue;const cross=(dir==='left'||dir==='right')?Math.abs(dy):Math.abs(dx);const axis=(dir==='left'||dir==='right')?Math.abs(dx):Math.abs(dy);const penalty=cross>Math.max(a.h,b.h)*2?700:0;const value=axis+cross*2.25+penalty;if(value<score){score=value;best=e}}if(best){setFocus(best);return}if(dir==='up'||dir==='down'){scrollBy({top:(dir==='up'?-1:1)*innerHeight*.68,behavior:'smooth'});setTimeout(()=>{const next=candidates().filter(visible);if(next.length){const cur=center(currentFocus);let nearest=null,d=Infinity;for(const e of next){if(e===currentFocus)continue;const b=center(e),v=Math.hypot(b.x-cur.x,b.y-cur.y);if(v<d){d=v;nearest=e}}if(nearest)setFocus(nearest,false)}},280)}else currentFocus.closest('.scroller,.genre-container,.cast-scroller,.server-buttons')?.scrollBy({left:(dir==='left'?-1:1)*innerWidth*.6,behavior:'smooth'})}
function closeLayer(){for(const s of ['.close-trailer-btn','.close-modal','#cfLiveClose','#cfMusicClose','#cfRadioClose','#cfActivityClose','.close-drawer','.cf-catalog-mobile-close']){const e=document.querySelector(s);if(visible(e)){e.click();return}}if(document.fullscreenElement){document.exitFullscreen?.();return}if(scrollY>10)scrollTo({top:0,behavior:'smooth'})}
function updateToggle(){const text=$('cfTvModeText'),icon=$('cfTvModeIcon');if(text)text.textContent=tvEnabled?'Exit TV Mode':'TV Mode';if(icon)icon.className=tvEnabled?'fa-solid fa-display':'fa-solid fa-tv'}
function installToggle(){const host=document.querySelector('.cf-install-drawer-section');if(!host||$('cfTvModeToggle'))return;host.insertAdjacentHTML('beforeend','<button id="cfTvModeToggle" class="drawer-item cf-tv-mode-toggle" type="button"><i id="cfTvModeIcon" class="fa-solid fa-tv"></i><span id="cfTvModeText">TV Mode</span></button>');$('cfTvModeToggle').addEventListener('click',()=>setTV(!tvEnabled));updateToggle()}
function setTV(on,persist=true){tvEnabled=!!on;document.documentElement.classList.toggle('cf304-tv',tvEnabled);document.body.classList.toggle('cf304-tv',tvEnabled);document.documentElement.classList.toggle('cf-tv-mode',tvEnabled);document.body.classList.toggle('cf-tv-mode',tvEnabled);if(persist)localStorage.setItem(MODE_KEY,tvEnabled?'on':'off');updateToggle();if(tvEnabled)setTimeout(firstFocus,180);else{document.querySelectorAll('.cf304-focus').forEach(x=>x.classList.remove('cf304-focus'));currentFocus=null}}
function key(e){const map={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(map[e.key]&&!tvEnabled){setTV(true,true)}if(!tvEnabled)return;const tag=(e.target.tagName||'').toLowerCase();if(['input','textarea','select'].includes(tag))return;if(map[e.key]){e.preventDefault();e.stopImmediatePropagation();move(map[e.key]);return}if(['Enter','NumpadEnter',' '].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();(currentFocus||document.activeElement)?.click?.();return}if(['Escape','Backspace','BrowserBack'].includes(e.key)||e.keyCode===461||e.keyCode===10009){e.preventDefault();e.stopImmediatePropagation();closeLayer()}}
function cleanHero(){const b=$('banner');if(!b)return;b.classList.add('cf304-cinematic','cf304-minimal');b.querySelectorAll('#cf304-kicker,#cf304-meta,#cf304-desc,#cf304-mylist,#cf304-trailer-toggle,.cf304-video').forEach(e=>e.remove());const buttons=b.querySelector('.banner-buttons');if(buttons)[...buttons.children].forEach((e,i)=>{if(i>0)e.remove()})}
function patchHero(){cleanHero();if(typeof window.setBanner==='function'&&!window.setBanner.__cf304minimal){const old=window.setBanner;window.setBanner=function(){const out=old.apply(this,arguments);setTimeout(cleanHero,0);return out};window.setBanner.__cf304minimal=true}}
function init(){cleanHero();patchHero();installToggle();const q=new URLSearchParams(location.search).get('tv'),saved=localStorage.getItem(MODE_KEY);setTV(q==='1'||(q!=='0'&&(saved==='on'||(saved!=='off'&&TV_UA.test(navigator.userAgent||'')))),false);document.addEventListener('keydown',key,true);document.addEventListener('focusin',e=>{if(tvEnabled&&e.target.matches?.(focusSelector))setFocus(e.target,false)});new MutationObserver(()=>{installToggle();patchHero();if(tvEnabled&&(!currentFocus||!visible(currentFocus)))setTimeout(firstFocus,80)}).observe(document.body,{childList:true,subtree:true});window.CineFlexTV={enable:()=>setTV(true),disable:()=>setTV(false),toggle:()=>setTV(!tvEnabled),isEnabled:()=>tvEnabled}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
