(() => {
'use strict';
const $=id=>document.getElementById(id);let trailerToken=0,trailerMuted=true,tvEnabled=false,currentFocus=null;
const TV_UA=/(android tv|google tv|smart-tv|smarttv|hbbtv|netcast|web0s|webos|tizen|viera|bravia|aftb|aftm|aftt|fire tv|roku|crkey|chromecast)/i;
const focusSelector='button:not([disabled]),a[href],[tabindex="0"],.drawer-item,.card,.movie-card,.dramabox-card,.netflix-item-container,.search-card,.cf-smart-card,.cf-top10-card,.cf51-because-card,.cf-catalog-card,.similar-card,.episode-card,.profile-card,.server-btn';
function typeOf(i){return i&&(i.media_type==='tv'||i.first_air_date||(!i.title&&i.name))?'tv':'movie'}
function currentItem(){return Array.isArray(window.trendingItems)?window.trendingItems[window.currentBannerIndex||0]:null}
function ensureHero(){const b=$('banner');if(!b)return;b.classList.add('cf304-cinematic');if(!b.querySelector('.cf304-backdrop'))b.insertAdjacentHTML('afterbegin','<div class="cf304-backdrop" aria-hidden="true"></div><div id="cf304-video" class="cf304-video" aria-hidden="true"></div>');const c=b.querySelector('.banner-content');if(!c)return;if(!$('cf304-kicker'))c.insertAdjacentHTML('afterbegin','<div id="cf304-kicker" class="cf304-kicker"><i class="fa-solid fa-clapperboard"></i><span>CINEFLEX FEATURED</span></div>');if(!$('cf304-meta'))$('banner-title')?.insertAdjacentHTML('afterend','<div id="cf304-meta" class="cf304-meta"></div><p id="cf304-desc" class="cf304-desc"></p>');const buttons=c.querySelector('.banner-buttons');if(buttons&&!$('cf304-mylist'))buttons.insertAdjacentHTML('beforeend','<button id="cf304-mylist" class="cf304-mylist" type="button"><i class="fa-solid fa-plus"></i> My List</button>');if(!$('cf304-trailer-toggle'))b.insertAdjacentHTML('beforeend','<button id="cf304-trailer-toggle" class="cf304-trailer-toggle" type="button" aria-label="Mute or unmute trailer"><i class="fa-solid fa-volume-xmark"></i></button>');$('cf304-mylist')?.addEventListener('click',toggleList);$('cf304-trailer-toggle')?.addEventListener('click',toggleMute)}
function toggleList(){const i=currentItem();if(!i)return;let list=[];try{list=JSON.parse(localStorage.getItem('cineflex_watchlist')||'[]')}catch{}const n=list.findIndex(x=>Number(x.id)===Number(i.id));if(n>=0)list.splice(n,1);else list.unshift(i);localStorage.setItem('cineflex_watchlist',JSON.stringify(list));window.watchlist=list;updateList(i);window.renderWatchlist?.()}
function updateList(i){const b=$('cf304-mylist');if(!b||!i)return;let list=[];try{list=JSON.parse(localStorage.getItem('cineflex_watchlist')||'[]')}catch{}const saved=list.some(x=>Number(x.id)===Number(i.id));b.classList.toggle('active',saved);b.innerHTML=saved?'<i class="fa-solid fa-check"></i> In My List':'<i class="fa-solid fa-plus"></i> My List'}
function toggleMute(){trailerMuted=!trailerMuted;const f=$('cf304-video')?.querySelector('iframe');const btn=$('cf304-trailer-toggle');if(btn)btn.innerHTML=`<i class="fa-solid fa-volume-${trailerMuted?'xmark':'high'}"></i>`;if(f){const src=new URL(f.src);src.searchParams.set('mute',trailerMuted?'1':'0');f.src=src.toString()}}
async function trailer(i){const box=$('cf304-video');if(!box||!i?.id||!window.BASE_URL||!window.API_KEY)return;const token=++trailerToken;box.classList.remove('active');box.innerHTML='';setTimeout(async()=>{try{const r=await fetch(`${window.BASE_URL}/${typeOf(i)}/${i.id}/videos?api_key=${window.API_KEY}`);const d=await r.json();if(token!==trailerToken)return;const vs=Array.isArray(d.results)?d.results:[];const v=vs.find(x=>x.site==='YouTube'&&/official trailer|trailer/i.test(`${x.name} ${x.type}`))||vs.find(x=>x.site==='YouTube'&&/teaser/i.test(`${x.name} ${x.type}`));if(!v?.key)return;box.innerHTML=`<iframe title="Muted cinematic trailer" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(v.key)}?autoplay=1&mute=${trailerMuted?1:0}&controls=0&disablekb=1&loop=1&playlist=${encodeURIComponent(v.key)}&playsinline=1&modestbranding=1&rel=0" allow="autoplay; encrypted-media"></iframe>`;requestAnimationFrame(()=>box.classList.add('active'))}catch{}},1900)}
function apply(i){ensureHero();if(!i)return;const b=$('banner'),back=b?.querySelector('.cf304-backdrop');if(back)back.style.backgroundImage=b.style.backgroundImage;const date=i.release_date||i.first_air_date||'';const year=date.slice(0,4)||'New';const score=Number(i.vote_average||0);$('cf304-meta').innerHTML=`<span class="match">${Math.max(75,Math.min(99,Math.round(score*10)||88))}% Match</span><span>${year}</span><span>${typeOf(i)==='tv'?'Series':'Movie'}</span><span class="quality">HD</span><span class="rating"><i class="fa-solid fa-star"></i> ${score?score.toFixed(1):'New'}</span>`;$('cf304-desc').textContent=i.overview||'Discover this featured title now on CineFlex.';updateList(i);trailer(i)}
function patch(){if(typeof window.setBanner!=='function'||window.setBanner.__cf304)return;const old=window.setBanner;window.setBanner=function(i){const b=$('banner');b?.classList.add('cf304-changing');const out=old.apply(this,arguments);setTimeout(()=>{apply(i);b?.classList.remove('cf304-changing')},100);return out};window.setBanner.__cf304=true}
function visible(e){if(!e||!e.isConnected)return false;const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity||1)>.05&&r.width>5&&r.height>5}
function scope(){const layers=[...document.querySelectorAll('.modal,.search-overlay,.menu-drawer,[role="dialog"]')].reverse();return layers.find(visible)||document}
function candidates(){return [...scope().querySelectorAll(focusSelector)].filter(visible)}
function focus(e,scroll=true){if(!e)return;document.querySelectorAll('.cf304-focus').forEach(x=>x.classList.remove('cf304-focus'));currentFocus=e;e.classList.add('cf304-focus');try{e.focus({preventScroll:true})}catch{e.focus?.()}if(scroll)e.scrollIntoView({behavior:'smooth',block:'center',inline:'center'})}
function center(e){const r=e.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2,h:r.height,w:r.width}}
function move(dir){const all=candidates();if(!all.length)return;if(!currentFocus||!all.includes(currentFocus)||!visible(currentFocus)){focus(all.find(e=>e.classList.contains('play-btn'))||all[0]);return}const a=center(currentFocus);let best=null,score=1e9;for(const e of all){if(e===currentFocus)continue;const b=center(e),dx=b.x-a.x,dy=b.y-a.y,p=dir==='left'?-dx:dir==='right'?dx:dir==='up'?-dy:dy;if(p<=7)continue;const cross=(dir==='left'||dir==='right')?Math.abs(dy):Math.abs(dx);const s=p+cross*2.6;if(s<score){score=s;best=e}}if(best)focus(best);else if(dir==='up'||dir==='down')scrollBy({top:(dir==='up'?-1:1)*innerHeight*.68,behavior:'smooth'});else currentFocus.closest('.scroller,.genre-container,.cast-scroller,.server-buttons')?.scrollBy({left:(dir==='left'?-1:1)*innerWidth*.6,behavior:'smooth'})}
function closeLayer(){for(const s of ['.close-trailer-btn','.close-modal','#cfLiveClose','#cfMusicClose','#cfRadioClose','#cfActivityClose','.close-drawer','.cf-catalog-mobile-close']){const e=document.querySelector(s);if(visible(e)){e.click();return}}if(document.fullscreenElement){document.exitFullscreen?.();return}if(scrollY>10)scrollTo({top:0,behavior:'smooth'})}
function key(e){if(!tvEnabled)return;const tag=(e.target.tagName||'').toLowerCase();if(['input','textarea','select'].includes(tag))return;const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(m[e.key]){e.preventDefault();e.stopImmediatePropagation();move(m[e.key]);return}if(['Enter','NumpadEnter',' '].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();(currentFocus||document.activeElement)?.click?.();return}if(['Escape','Backspace','BrowserBack'].includes(e.key)||e.keyCode===461||e.keyCode===10009){e.preventDefault();e.stopImmediatePropagation();closeLayer()}}
function setTV(on,persist=true){tvEnabled=!!on;document.documentElement.classList.toggle('cf304-tv',tvEnabled);document.body.classList.toggle('cf304-tv',tvEnabled);document.body.classList.remove('cf-tv-mode');if(persist)localStorage.setItem('cineflex_tv_mode',tvEnabled?'on':'off');if(tvEnabled)setTimeout(()=>focus(candidates().find(e=>e.classList.contains('play-btn'))||candidates()[0],false),600)}
function init(){ensureHero();patch();const wait=setInterval(()=>{patch();const i=currentItem();if(i){apply(i);clearInterval(wait)}},300);setTimeout(()=>clearInterval(wait),12000);document.body.insertAdjacentHTML('beforeend','<div class="cf304-tv-badge"><i class="fa-solid fa-tv"></i> TV REMOTE MODE</div>');const q=new URLSearchParams(location.search).get('tv');const saved=localStorage.getItem('cineflex_tv_mode');setTV(q==='1'||(q!=='0'&&saved!=='off'&&(saved==='on'||TV_UA.test(navigator.userAgent||''))),false);document.addEventListener('keydown',key,true);document.addEventListener('focusin',e=>{if(tvEnabled&&e.target.matches?.(focusSelector))focus(e.target,false)});window.CineFlexTV={enable:()=>setTV(true),disable:()=>setTV(false),toggle:()=>setTV(!tvEnabled),isEnabled:()=>tvEnabled}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
