(function(){
  'use strict';
  const CHANNELS=[
    {id:'ptv',name:'PTV Philippines',short:'PTV',type:'Government / News',url:'https://www.youtube.com/@ptvph/streams'},
    {id:'untv',name:'UNTV News and Rescue',short:'UNTV',type:'News / Public Service',url:'https://www.youtube.com/@UNTVNewsandRescue/streams'},
    {id:'net25',name:'NET25',short:'NET25',type:'News / Entertainment',url:'https://www.youtube.com/@NET25TV/streams'},
    {id:'kapamilya',name:'Kapamilya Online Live',short:'KOL',type:'Entertainment',url:'https://www.youtube.com/@abscbnentertainment/streams'},
    {id:'gmanews',name:'GMA Integrated News',short:'GMA',type:'News / Special Coverage',url:'https://www.youtube.com/@gmanews/streams'},
    {id:'news5',name:'News5Everywhere',short:'NEWS5',type:'News / Public Affairs',url:'https://www.youtube.com/@News5Everywhere/streams'},
    {id:'senate',name:'Senate of the Philippines',short:'SENATE',type:'Government',url:'https://www.youtube.com/@SenatePhilippines/streams'},
    {id:'house',name:'House of Representatives',short:'HOUSE',type:'Government',url:'https://www.youtube.com/@HouseofRepsPH/streams'}
  ];
  function markup(){return `<section id="cfLiveTvShell" class="cf-live-tv-shell" aria-hidden="true"><header class="cf-live-tv-head"><div class="cf-live-tv-brand"><i class="fa-solid fa-tower-broadcast"></i><div><h2>CineFlex Live TV</h2><small>Official Philippine channel sources</small></div></div><button class="cf-live-tv-close" type="button" onclick="cfCloseLiveTV()"><i class="fa-solid fa-xmark"></i></button></header><main class="cf-live-tv-wrap"><div class="cf-live-tv-hero"><div class="cf-live-tv-feature"><h1>Philippine Live TV</h1><p>News, public service, government coverage, and entertainment from official broadcaster pages.</p></div><div class="cf-live-tv-stats"><strong>${CHANNELS.length}</strong><span>official channel shortcuts</span></div></div><div class="cf-live-tv-title"><h3>PH Channels</h3><span>Availability depends on broadcaster schedule</span></div><div class="cf-live-tv-grid">${CHANNELS.map(c=>`<button class="cf-live-card" type="button" onclick="cfPlayLiveChannel('${c.id}')"><span class="cf-live-badge">LIVE</span><span class="cf-live-logo">${c.short}</span><h4>${c.name}</h4><p>${c.type}</p></button>`).join('')}</div></main></section><div id="cfLivePlayer" class="cf-live-player" aria-hidden="true"><div class="cf-live-player-card"><div class="cf-live-player-top"><h3 id="cfLivePlayerTitle">Live channel</h3><button class="cf-live-player-close" onclick="cfCloseLivePlayer()"><i class="fa-solid fa-xmark"></i></button></div><div class="cf-live-screen"><div><i class="fa-solid fa-circle-play"></i><h3 id="cfLivePlayerName"></h3><p>For reliability and broadcaster compliance, this channel opens through its official live page. Direct playback may be added later only when an authorized embeddable stream is available.</p><div class="cf-live-actions"><a id="cfLiveOfficialLink" class="cf-live-primary" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-arrow-up-right-from-square"></i> Watch Official Live</a><button class="cf-live-secondary" onclick="cfCloseLivePlayer()">Back to Channels</button></div></div></div><div class="cf-live-note">CineFlex does not restream or host these TV broadcasts.</div></div></div>`}
  function init(){if(document.getElementById('cfLiveTvShell'))return;document.body.insertAdjacentHTML('beforeend',markup());}
  window.cfOpenLiveTV=function(){init();const e=document.getElementById('cfLiveTvShell');e.classList.add('active');e.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(typeof closeMenuDrawer==='function')closeMenuDrawer();};
  window.cfCloseLiveTV=function(){const e=document.getElementById('cfLiveTvShell');if(e)e.classList.remove('active');document.body.style.overflow='';};
  window.cfPlayLiveChannel=function(id){const c=CHANNELS.find(x=>x.id===id);if(!c)return;document.getElementById('cfLivePlayerTitle').textContent=c.name;document.getElementById('cfLivePlayerName').textContent=c.name;document.getElementById('cfLiveOfficialLink').href=c.url;const p=document.getElementById('cfLivePlayer');p.classList.add('active');p.setAttribute('aria-hidden','false');};
  window.cfCloseLivePlayer=function(){const p=document.getElementById('cfLivePlayer');if(p)p.classList.remove('active');};
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){cfCloseLivePlayer();cfCloseLiveTV();}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
