(()=>{'use strict';
const KEY='cineflex_tv_mode_v15';
const SELECTOR=['button:not([disabled])','a[href]','[tabindex]:not([tabindex="-1"])','.card','.search-card','.drawer-item','.cf-catalog-card','.cf-live-card','.cf-music-card','.cf-radio-card','.cf-activity-card'].join(',');
let toastTimer=0;
const visible=el=>{if(!el||el.closest('[aria-hidden="true"]'))return false;const s=getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>4&&r.height>4};
function toast(msg){let n=document.getElementById('cf15Toast');if(!n){n=document.createElement('div');n.id='cf15Toast';n.className='cf15-toast';document.body.appendChild(n)}n.textContent=msg;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),1800)}
function setMode(on,announce=true){document.body.classList.toggle('cf-tv-mode',on);localStorage.setItem(KEY,on?'1':'0');const t=document.getElementById('cf15TvToggle');if(t)t.setAttribute('aria-pressed',String(on));if(announce)toast(on?'TV Mode enabled — use arrow keys and Enter':'TV Mode disabled')}
function enhance(root=document){root.querySelectorAll(SELECTOR).forEach(el=>{if(el.matches('.drawer-item,.card,.search-card,.cf-live-card,.cf-music-card,.cf-radio-card')&&!el.hasAttribute('tabindex'))el.tabIndex=0;el.classList.add('cf15-focusable')})}
function candidates(){return [...document.querySelectorAll(SELECTOR)].filter(visible)}
function center(el){const r=el.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}}
function move(dir){enhance();const items=candidates();if(!items.length)return;let cur=document.activeElement;if(!items.includes(cur)){items[0].focus({preventScroll:false});return}const a=center(cur);let best=null,score=Infinity;for(const el of items){if(el===cur)continue;const b=center(el),dx=b.x-a.x,dy=b.y-a.y;if(dir==='left'&&dx>=-4||dir==='right'&&dx<=4||dir==='up'&&dy>=-4||dir==='down'&&dy<=4)continue;const primary=(dir==='left'||dir==='right')?Math.abs(dx):Math.abs(dy);const cross=(dir==='left'||dir==='right')?Math.abs(dy):Math.abs(dx);const s=primary+cross*2.35;if(s<score){score=s;best=el}}if(best){best.focus({preventScroll:true});best.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'})}}
function back(){const closers=['#cfLiveClose','#cfMusicClose','#cfRadioClose','#cfActivityClose','.modal .close','.close-drawer','.cf-catalog-mobile-close'];for(const sel of closers){const el=document.querySelector(sel);if(visible(el)){el.click();return true}}if(document.fullscreenElement){document.exitFullscreen?.();return true}return false}
function key(e){const tag=(e.target.tagName||'').toLowerCase();if(['input','textarea','select'].includes(tag))return;const arrows={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(arrows[e.key]){if(!document.body.classList.contains('cf-tv-mode'))setMode(true,false);e.preventDefault();move(arrows[e.key]);return}if(['Enter',' ','NumpadEnter'].includes(e.key)){const el=document.activeElement;if(el&&el!==document.body){e.preventDefault();el.click()}return}if(['Escape','Backspace','BrowserBack'].includes(e.key)){if(back())e.preventDefault();return}if(e.key==='Home'){e.preventDefault();window.scrollTo({top:0,behavior:'smooth'});document.querySelector('.logo,button,a')?.focus()}}
function build(){if(!document.getElementById('cf15TvBadge'))document.body.insertAdjacentHTML('beforeend','<div id="cf15TvBadge" class="cf15-tv-badge"><i class="fa-solid fa-tv"></i> TV MODE</div>');const activity=document.querySelector('.drawer-item[onclick*="cfOpenActivity"]');if(activity&&!document.getElementById('cf15TvToggle'))activity.insertAdjacentHTML('afterend','<button id="cf15TvToggle" class="drawer-item cf15-tv-toggle" type="button" aria-pressed="false"><i class="fa-solid fa-gamepad"></i> Smart TV Mode <span class="cf15-switch" aria-hidden="true"></span></button>');document.getElementById('cf15TvToggle')?.addEventListener('click',()=>setMode(!document.body.classList.contains('cf-tv-mode')));enhance();setMode(localStorage.getItem(KEY)==='1',false)}
document.addEventListener('keydown',key,true);document.addEventListener('focusin',e=>{document.querySelectorAll('.cf15-remote-focus').forEach(x=>x.classList.remove('cf15-remote-focus'));if(document.body.classList.contains('cf-tv-mode')&&e.target.matches?.(SELECTOR))e.target.classList.add('cf15-remote-focus')});new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(n=>n.nodeType===1&&enhance(n)))).observe(document.documentElement,{childList:true,subtree:true});window.cfToggleTvMode=()=>setMode(!document.body.classList.contains('cf-tv-mode'));document.readyState==='loading'?document.addEventListener('DOMContentLoaded',build):build();
})();
