(() => {
'use strict';
const ROOMS='watchPartyRooms', MAX_CHAT=80;
let roomId='', roomData=null, unsubRoom=null, unsubChat=null, unsubMembers=null, presenceTimer=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const user=()=>window.auth?.currentUser||null;
const profile=()=>{try{return JSON.parse(localStorage.getItem('cineflex_profile'))||{}}catch{return {}}};
const mediaType=i=>i?.media_type||(i?.first_air_date||i?.name?'tv':'movie');
const title=i=>i?.title||i?.name||'CineFlex Watch Party';
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
function toast(t){let n=$('.cf-party-toast');if(!n){n=document.createElement('div');n.className='cf-party-toast';document.body.appendChild(n)}n.textContent=t;n.classList.add('show');clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove('show'),2300)}
function requireUser(cb){if(user())return cb(); if(typeof window.openLoginModal==='function')window.openLoginModal(); toast('Mag-login muna para sumali sa Watch Party.');}
function currentMedia(){const i=window.currentItem;if(!i?.id)return null;return {id:i.id,title:title(i),mediaType:mediaType(i),poster_path:i.poster_path||'',backdrop_path:i.backdrop_path||'',season:Number(window.currentTVState?.currentSeason||1),episode:Number(window.currentTVState?.currentEpNum||1)};}
function shell(){if($('#cf-party-shell'))return;document.body.insertAdjacentHTML('beforeend',`<button class="cf-party-fab" id="cf-party-fab" type="button"><i class="fa-solid fa-users-viewfinder"></i><span>Watch Party</span></button><div class="cf-party-shell" id="cf-party-shell"><div class="cf-party-panel"><main class="cf-party-main"><header class="cf-party-head"><div class="cf-party-title"><span class="cf-party-kicker">CineFlex Together</span><h2>Watch Party Lounge</h2><div class="cf-party-status" id="cf-party-status">Create or join a room.</div></div><button class="cf-party-close" id="cf-party-close">×</button></header><section class="cf-party-hero" id="cf-party-hero"><div class="cf-party-hero-content"><span class="cf-party-code" id="cf-party-code">NO ROOM</span><h3 id="cf-party-media-title">Choose a movie, then create a party.</h3><p id="cf-party-host-note">Real-time room, presence, reactions, and chat.</p></div></section><div class="cf-party-actions"><button class="cf-party-btn primary" id="cf-create-room"><i class="fa-solid fa-plus"></i> Create Room</button><button class="cf-party-btn" id="cf-copy-room"><i class="fa-solid fa-link"></i> Copy Invite</button><button class="cf-party-btn" id="cf-host-sync"><i class="fa-solid fa-rotate"></i> Start / Resync</button><button class="cf-party-btn danger" id="cf-leave-room"><i class="fa-solid fa-right-from-bracket"></i> Leave</button></div><div class="cf-party-join"><input class="cf-party-input" id="cf-room-input" maxlength="6" placeholder="Enter 6-character room code"><button class="cf-party-btn" id="cf-join-room">Join</button></div><div class="cf-party-grid"><article class="cf-party-card"><strong><i class="fa-solid fa-user-group"></i> Participants</strong><span id="cf-party-count">0 online</span><div class="cf-party-members" id="cf-party-members"></div></article><article class="cf-party-card"><strong><i class="fa-solid fa-satellite-dish"></i> Host Controls</strong><span id="cf-party-sync-state">Waiting for room.</span><div class="cf-party-actions"><button class="cf-party-btn" data-react="🔥">🔥</button><button class="cf-party-btn" data-react="❤️">❤️</button><button class="cf-party-btn" data-react="😂">😂</button><button class="cf-party-btn" data-react="😮">😮</button></div></article></div></main><aside class="cf-party-side"><div class="cf-chat-head"><i class="fa-solid fa-comments"></i> Party Chat</div><div class="cf-chat-list" id="cf-chat-list"><div class="cf-chat-empty">Join a room to start chatting.</div></div><form class="cf-chat-compose" id="cf-chat-form"><input class="cf-party-input" id="cf-chat-input" maxlength="280" placeholder="Message the party..."><button class="cf-party-btn primary" aria-label="Send"><i class="fa-solid fa-paper-plane"></i></button></form></aside></div></div>`);
$('#cf-party-fab').onclick=open;$('#cf-party-close').onclick=close;$('#cf-party-shell').addEventListener('click',e=>{if(e.target.id==='cf-party-shell')close()});$('#cf-create-room').onclick=()=>requireUser(createRoom);$('#cf-join-room').onclick=()=>requireUser(()=>joinRoom($('#cf-room-input').value));$('#cf-copy-room').onclick=copyInvite;$('#cf-host-sync').onclick=hostSync;$('#cf-leave-room').onclick=leaveRoom;$('#cf-chat-form').onsubmit=e=>{e.preventDefault();sendChat($('#cf-chat-input').value)};document.querySelectorAll('[data-react]').forEach(b=>b.onclick=()=>sendChat(b.dataset.react,true));
const q=new URLSearchParams(location.search).get('party');if(q){$('#cf-room-input').value=q.toUpperCase();setTimeout(()=>requireUser(()=>joinRoom(q)),1200)}
}
function open(){shell();$('#cf-party-shell').classList.add('open');document.body.style.overflow='hidden'}function close(){$('#cf-party-shell')?.classList.remove('open');document.body.style.overflow=''}
function refs(id=roomId){return window.db.collection(ROOMS).doc(id)}
async function createRoom(){const media=currentMedia();if(!media){toast('Buksan muna ang movie o episode na gusto mong panoorin.');return}const id=code(),u=user(),p=profile();await refs(id).set({code:id,hostUid:u.uid,hostName:p.name||u.displayName||'Host',media,status:'waiting',commandVersion:0,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await joinRoom(id);toast(`Room ${id} created.`)}
async function joinRoom(raw){const id=String(raw||'').trim().toUpperCase();if(id.length!==6){toast('Kailangan ng 6-character room code.');return}const snap=await refs(id).get();if(!snap.exists){toast('Hindi makita ang room na iyon.');return}cleanup();roomId=id;await upsertPresence();subscribe();history.replaceState({},'',`${location.pathname}?party=${id}`);toast(`Joined room ${id}.`)}
async function upsertPresence(){if(!roomId||!user())return;const u=user(),p=profile();await refs().collection('members').doc(u.uid).set({name:p.name||u.displayName||'Viewer',avatar:p.avatar||u.photoURL||'icon-192.png',isHost:roomData?.hostUid===u.uid,lastSeen:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});clearInterval(presenceTimer);presenceTimer=setInterval(()=>refs().collection('members').doc(u.uid).set({lastSeen:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}).catch(()=>{}),25000)}
function subscribe(){unsubRoom=refs().onSnapshot(s=>{if(!s.exists){toast('The party room has ended.');leaveRoom();return}const prev=roomData;roomData=s.data();renderRoom();upsertPresence();if(prev&&roomData.commandVersion>prev.commandVersion&&roomData.hostUid!==user()?.uid)applyCommand(roomData)});unsubMembers=refs().collection('members').onSnapshot(s=>renderMembers(s.docs.map(d=>({id:d.id,...d.data()}))));unsubChat=refs().collection('messages').orderBy('createdAt','asc').limitToLast(MAX_CHAT).onSnapshot(s=>renderChat(s.docs.map(d=>d.data())))}
function renderRoom(){shell();const m=roomData?.media||{};$('#cf-party-code').textContent=roomId||'NO ROOM';$('#cf-party-media-title').textContent=m.title||'No title selected';$('#cf-party-host-note').textContent=`Hosted by ${roomData?.hostName||'CineFlex user'}`;$('#cf-party-status').textContent=roomData?.status==='playing'?'Party started • synchronized room active':'Room ready • waiting for host';$('#cf-party-sync-state').textContent=user()?.uid===roomData?.hostUid?'You are the host. Open the title and press Start / Resync.':'Host controls the shared title and sync command.';const path=m.backdrop_path||m.poster_path;$('#cf-party-hero').style.backgroundImage=path?`linear-gradient(0deg,rgba(5,5,9,.9),rgba(5,5,9,.1)),url(https://image.tmdb.org/t/p/original${path})`:'';$('#cf-host-sync').style.display=user()?.uid===roomData?.hostUid?'inline-flex':'none';$('#cf-party-fab')?.classList.add('online')}
function renderMembers(items){$('#cf-party-count').textContent=`${items.length} online`;$('#cf-party-members').innerHTML=items.map(m=>`<span class="cf-party-member"><img src="${esc(m.avatar||'icon-192.png')}" onerror="this.src='icon-192.png'"><span>${esc(m.name)}${m.id===roomData?.hostUid?' 👑':''}</span></span>`).join('')}
function renderChat(items){const el=$('#cf-chat-list');if(!items.length){el.innerHTML='<div class="cf-chat-empty">No messages yet. Say hello!</div>';return}el.innerHTML=items.map(m=>`<div class="cf-chat-msg"><img src="${esc(m.avatar||'icon-192.png')}" onerror="this.src='icon-192.png'"><div class="cf-chat-bubble"><b>${esc(m.name)}</b><p>${esc(m.text)}</p><time>${m.createdAt?.toDate?m.createdAt.toDate().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</time></div></div>`).join('');el.scrollTop=el.scrollHeight}
async function sendChat(text,reaction=false){text=String(text||'').trim();if(!roomId||!user()||!text)return;const u=user(),p=profile();await refs().collection('messages').add({uid:u.uid,name:p.name||u.displayName||'Viewer',avatar:p.avatar||u.photoURL||'icon-192.png',text:text.slice(0,reaction?8:280),reaction:!!reaction,createdAt:firebase.firestore.FieldValue.serverTimestamp()});$('#cf-chat-input').value=''}
async function hostSync(){if(!roomId||user()?.uid!==roomData?.hostUid){toast('Host-only control.');return}const media=currentMedia()||roomData.media;if(!media){toast('Open the party movie first.');return}await refs().set({media,status:'playing',command:'sync',commandVersion:Number(roomData.commandVersion||0)+1,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});toast('Sync command sent to everyone.')}
async function applyCommand(data){const m=data.media;if(!m?.id)return;toast(`Host started ${m.title}.`);try{if(!window.currentItem||window.currentItem.id!==m.id){const details=await fetch(`${window.BASE_URL||'https://api.themoviedb.org/3'}/${m.mediaType}/${m.id}?api_key=${window.API_KEY}&language=en-US`).then(r=>r.json());details.media_type=m.mediaType;await window.showDetails(details)}if(m.mediaType==='tv'&&window.currentTVState){window.currentTVState.currentSeason=m.season||1;window.currentTVState.currentEpNum=m.episode||1}setTimeout(()=>{if(typeof window.startPlayback==='function')window.startPlayback()},500)}catch(e){console.warn('Party sync could not open title',e)}}
async function copyInvite(){if(!roomId){toast('Create or join a room first.');return}const url=`${location.origin}${location.pathname}?party=${roomId}`;try{await navigator.clipboard.writeText(url);toast('Invite link copied.')}catch{prompt('Copy this invite link:',url)}}
async function leaveRoom(){const u=user();if(roomId&&u)await refs().collection('members').doc(u.uid).delete().catch(()=>{});cleanup();roomId='';roomData=null;history.replaceState({},'',location.pathname);$('#cf-party-fab')?.classList.remove('online');if($('#cf-party-code')){$('#cf-party-code').textContent='NO ROOM';$('#cf-party-media-title').textContent='Choose a movie, then create a party.';$('#cf-party-members').innerHTML='';$('#cf-chat-list').innerHTML='<div class="cf-chat-empty">Join a room to start chatting.</div>'}toast('Left the Watch Party.')}
function cleanup(){[unsubRoom,unsubChat,unsubMembers].forEach(f=>{try{f&&f()}catch{}});unsubRoom=unsubChat=unsubMembers=null;clearInterval(presenceTimer)}
window.addEventListener('beforeunload',()=>{if(roomId&&user())refs().collection('members').doc(user().uid).delete().catch(()=>{})});document.addEventListener('DOMContentLoaded',shell);
window.CineFlexParty={open,createRoom,joinRoom,leaveRoom};
})();
