(() => {
'use strict';
const $=id=>document.getElementById(id); let latestNoticeAt=0; let unsubNotices=null;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){let e=$('cf42Toast');if(!e){e=document.createElement('div');e.id='cf42Toast';e.className='cf42-toast';document.body.appendChild(e)}e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function user(){return window.auth&&auth.currentUser}
function requireUser(){if(user())return true;if(typeof openLoginModal==='function')openLoginModal();toast('Mag-login muna para mag-submit.');return false}
function selectedMedia(){const i=window.currentItem||null,s=window.currentTVState||{};return i?{tmdbId:i.id,title:i.title||i.name||'',mediaType:(i.first_air_date||i.name||i.media_type==='tv')?'tv':'movie',season:s.season||null,episode:s.episode||null}:null}
function open(tab='request'){$('cf42Modal').classList.add('open');switchTab(tab)}
function close(){$('cf42Modal').classList.remove('open')}
function switchTab(tab){document.querySelectorAll('.cf42-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.cf42-pane').forEach(p=>p.classList.toggle('active',p.id===`cf42-${tab}`));if(tab==='notifications')$('cf42Dot').classList.remove('show')}
async function submitRequest(e){e.preventDefault();if(!requireUser())return;const u=user();const data={type:$('cf42ReqType').value,title:$('cf42ReqTitle').value.trim(),notes:$('cf42ReqNotes').value.trim(),status:'pending',uid:u.uid,userEmail:u.email||'',userName:u.displayName||'CineFlex User',createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!data.title)return toast('Ilagay ang title.');await db.collection('contentRequests').add(data);e.target.reset();toast('Naipadala na ang request.');}
async function submitReport(e){e.preventDefault();if(!requireUser())return;const u=user(),m=selectedMedia();const data={category:$('cf42ReportType').value,details:$('cf42ReportDetails').value.trim(),status:'pending',uid:u.uid,userEmail:u.email||'',userName:u.displayName||'CineFlex User',media:m||{},pageUrl:location.href,userAgent:navigator.userAgent,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};await db.collection('brokenLinkReports').add(data);e.target.reset();toast('Naipadala na ang report. Salamat!');}
function listenNotices(){if(!window.db)return;unsubNotices=db.collection('cineflexNotifications').where('active','==',true).orderBy('createdAt','desc').limit(10).onSnapshot(s=>{const box=$('cf42NoticeList');if(!box)return;const rows=[];s.forEach(d=>{const x=d.data();const ts=x.createdAt?.toMillis?.()||0;if(ts>latestNoticeAt&&latestNoticeAt>0)$('cf42Dot').classList.add('show');latestNoticeAt=Math.max(latestNoticeAt,ts);rows.push(`<div class="cf42-notice"><b>${esc(x.title||'CineFlex Update')}</b><div>${esc(x.message||'')}</div><small>${x.createdAt?.toDate?.().toLocaleString?.()||'Just now'}</small></div>`)});box.innerHTML=rows.join('')||'<p class="cf42-note">Wala pang notifications.</p>'},()=>{})}
function injectReportButton(){const target=document.querySelector('.modal-buttons,.modal-actions,#modal-actions');if(!target||$('cf42InlineReport'))return;const b=document.createElement('button');b.id='cf42InlineReport';b.className='cf42-report-btn';b.innerHTML='<i class="fa-solid fa-triangle-exclamation"></i> Report';b.onclick=()=>open('report');target.appendChild(b)}
function build(){document.body.insertAdjacentHTML('beforeend',`<button class="cf42-fab" id="cf42Fab" aria-label="Requests and notifications"><i class="fa-solid fa-bell"></i><span id="cf42Dot" class="cf42-dot"></span></button><div id="cf42Modal" class="cf42-modal"><div class="cf42-card"><div class="cf42-head"><div><h2>CineFlex Center</h2><div class="cf42-note">Requests, reports, at platform updates</div></div><button class="cf42-close" id="cf42Close">×</button></div><div class="cf42-tabs"><button data-tab="request" class="active">Request Content</button><button data-tab="report">Report Link</button><button data-tab="notifications">Notifications</button></div><section id="cf42-request" class="cf42-pane active"><form id="cf42RequestForm"><div class="cf42-field"><label>Request type</label><select id="cf42ReqType"><option value="movie">Movie</option><option value="tv">TV Series</option><option value="anime">Anime</option></select></div><div class="cf42-field"><label>Title</label><input id="cf42ReqTitle" maxlength="120" placeholder="Title ng gusto mong idagdag" required></div><div class="cf42-field"><label>Notes (optional)</label><textarea id="cf42ReqNotes" maxlength="500" placeholder="Year, language, episode, o ibang detalye"></textarea></div><button class="cf42-submit">Send Request</button></form></section><section id="cf42-report" class="cf42-pane"><form id="cf42ReportForm"><div class="cf42-field"><label>Problem</label><select id="cf42ReportType"><option value="not-playing">Video not playing</option><option value="wrong-title">Wrong title or episode</option><option value="buffering">Buffering / very slow</option><option value="audio-subtitle">Audio or subtitle issue</option><option value="other">Other issue</option></select></div><div class="cf42-field"><label>Details</label><textarea id="cf42ReportDetails" maxlength="500" placeholder="Ano ang nangyari?"></textarea></div><p class="cf42-note">Automatic na isasama ang selected movie/episode at device information.</p><button class="cf42-submit">Submit Report</button></form></section><section id="cf42-notifications" class="cf42-pane"><div id="cf42NoticeList"><p class="cf42-note">Loading notifications…</p></div></section></div></div>`);$('cf42Fab').onclick=()=>open('notifications');$('cf42Close').onclick=close;$('cf42Modal').addEventListener('click',e=>{if(e.target.id==='cf42Modal')close()});document.querySelectorAll('.cf42-tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('cf42RequestForm').onsubmit=submitRequest;$('cf42ReportForm').onsubmit=submitReport;setInterval(injectReportButton,1200);listenNotices();window.cfOpenContentCenter=open}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();
