(() => {
'use strict';
const KEY='cineflex_progression_v34';
const ACH=[
 {id:'pioneer',icon:'🌟',name:'CineFlex Pioneer',desc:'Join the Build 3.4 era',test:s=>true,reward:100},
 {id:'first_play',icon:'🎬',name:'First Screening',desc:'Start your first title',test:s=>s.stats.plays>=1,reward:75},
 {id:'movie_buff',icon:'🍿',name:'Movie Buff',desc:'Start 10 titles',test:s=>s.stats.plays>=10,reward:250},
 {id:'critic',icon:'⭐',name:'CineCritic',desc:'Rate 5 titles',test:s=>s.stats.ratings>=5,reward:180},
 {id:'social',icon:'💬',name:'Social Viewer',desc:'Post 10 comments or party chats',test:s=>s.stats.social>=10,reward:220},
 {id:'party_host',icon:'🎉',name:'Party Host',desc:'Create a Watch Party',test:s=>s.stats.parties>=1,reward:140},
 {id:'streak7',icon:'🔥',name:'Seven-Day Flame',desc:'Reach a 7-day login streak',test:s=>s.streak>=7,reward:350},
 {id:'level10',icon:'👑',name:'CineFlex Elite',desc:'Reach Level 10',test:s=>levelFor(s.xp).level>=10,reward:500}
];
let state=null,saveTimer=null,cloudReady=false;
const $=s=>document.querySelector(s);
const today=()=>new Date().toISOString().slice(0,10);
const yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};
function base(){return {xp:0,coins:0,streak:0,lastLogin:'',claimedDays:[],unlocked:[],stats:{plays:0,ratings:0,social:0,parties:0,watchMinutes:0},createdAt:Date.now(),updatedAt:Date.now()}}
function merge(a,b){const n={...a,...b};n.stats={...a.stats,...(b?.stats||{})};n.unlocked=Array.isArray(b?.unlocked)?b.unlocked:[];n.claimedDays=Array.isArray(b?.claimedDays)?b.claimedDays:[];return n}
function load(){try{state=merge(base(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{state=base()} return state}
function levelFor(xp){let level=1,used=0,need=400;while(xp>=used+need){used+=need;level++;need=Math.round(400*Math.pow(level,1.32))}return {level,current:xp-used,need,totalFloor:used,percent:Math.min(100,((xp-used)/need)*100)}}
function profileId(){return localStorage.getItem('cineflex_profile')||'default'}
function user(){return window.auth?.currentUser||null}
function cloudRef(){const u=user();if(!u||!window.db)return null;return db.collection('users').doc(u.uid).collection('profiles').doc(profileId()).collection('system').doc('progression')}
function save(){state.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(state));render();clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const r=cloudRef();if(r)await r.set(state,{merge:true})}catch(e){console.warn('Progression cloud save:',e.message||e)}},500)}
async function syncCloud(){try{const r=cloudRef();if(!r)return;const snap=await r.get();if(snap.exists){const cloud=merge(base(),snap.data());state=cloud.updatedAt>state.updatedAt?cloud:state}else await r.set(state,{merge:true});cloudReady=true;save()}catch(e){console.warn('Progression cloud sync:',e.message||e)}}
function toast(text){let el=$('.cf-xp-toast');if(!el){el=document.createElement('div');el.className='cf-xp-toast';document.body.appendChild(el)}el.textContent=text;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)}
function addXP(amount,reason,coins=0){amount=Math.max(0,Number(amount)||0);coins=Math.max(0,Number(coins)||0);const before=levelFor(state.xp).level;state.xp+=amount;state.coins+=coins;checkAchievements();save();const after=levelFor(state.xp).level;toast(`+${amount} XP${coins?` • +${coins} CineCoins`:''} — ${reason}`);if(after>before)setTimeout(()=>toast(`Level Up! Welcome to Level ${after} 👑`),700)}
function stat(name,inc=1,xp=0,reason='',coins=0){state.stats[name]=(state.stats[name]||0)+inc;if(xp)addXP(xp,reason,coins);else{checkAchievements();save()}}
function checkAchievements(){for(const a of ACH){if(!state.unlocked.includes(a.id)&&a.test(state)){state.unlocked.push(a.id);state.xp+=a.reward;state.coins+=Math.max(25,Math.round(a.reward/4));setTimeout(()=>toast(`Achievement unlocked: ${a.icon} ${a.name}`),400)}}}
function daily(){const d=today();if(state.lastLogin===d)return;if(state.lastLogin===yesterday())state.streak+=1;else state.streak=1;state.lastLogin=d;const xp=50+Math.min(150,(state.streak-1)*15),coins=25+Math.min(75,(state.streak-1)*5);state.xp+=xp;state.coins+=coins;state.claimedDays.push(d);checkAchievements();save();showReward(xp,coins)}
function showReward(xp,coins){shell();$('#cf-reward-xp').textContent=`+${xp} XP`;$('#cf-reward-coins').textContent=`+${coins} CineCoins`;$('#cf-reward-streak').textContent=`Day ${state.streak} Streak`;$('#cf-daily-reward').classList.add('open')}
function shell(){if($('#cf-progress-shell'))return;document.body.insertAdjacentHTML('beforeend',`<button class="cf-progress-fab" id="cf-progress-fab" title="My CineFlex Progress"><i class="fa-solid fa-trophy"></i><b id="cf-level-mini">1</b></button><div class="cf-progress-shell" id="cf-progress-shell"><section class="cf-progress-panel"><header class="cf-progress-head"><div><span class="cf-progress-kicker">MY CINEFLEX JOURNEY</span><h2>Progress & Rewards</h2></div><button class="cf-progress-close" id="cf-progress-close">×</button></header><div class="cf-progress-body"><div class="cf-level-card"><div class="cf-level-orb"><div><span>LEVEL</span><b id="cf-level">1</b></div></div><div class="cf-level-copy"><h3 id="cf-rank">New Viewer</h3><div class="cf-xp-track"><div class="cf-xp-fill" id="cf-xp-fill"></div></div><div class="cf-xp-meta"><span id="cf-xp-current">0 XP</span><span id="cf-xp-next">400 XP to next</span></div></div><div class="cf-coins"><span>CineCoins</span><b id="cf-coins">0 🪙</b></div></div><div class="cf-progress-grid"><div class="cf-stat"><span>Titles Started</span><b id="cf-stat-plays">0</b></div><div class="cf-stat"><span>Ratings</span><b id="cf-stat-ratings">0</b></div><div class="cf-stat"><span>Social Actions</span><b id="cf-stat-social">0</b></div><div class="cf-stat"><span>Login Streak</span><b id="cf-stat-streak">0 days</b></div></div><div class="cf-achievements-title"><div><span class="cf-progress-kicker">COLLECTION</span><h3>Achievements</h3></div><span id="cf-ach-count">0 unlocked</span></div><div class="cf-achievements" id="cf-achievements"></div></div></section></div><div class="cf-reward" id="cf-daily-reward"><div class="cf-reward-card"><div class="cf-reward-icon">🎁</div><span class="cf-progress-kicker">DAILY REWARD</span><h2>Welcome back!</h2><p id="cf-reward-streak">Day 1 Streak</p><div class="cf-reward-values"><b id="cf-reward-xp">+50 XP</b><b id="cf-reward-coins">+25 CineCoins</b></div><button id="cf-reward-close">Claim & Continue</button></div></div>`);$('#cf-progress-fab').onclick=open;$('#cf-progress-close').onclick=close;$('#cf-progress-shell').onclick=e=>{if(e.target.id==='cf-progress-shell')close()};$('#cf-reward-close').onclick=()=>$('#cf-daily-reward').classList.remove('open')}
function rank(l){if(l>=20)return'CineFlex Legend';if(l>=15)return'Elite Binger';if(l>=10)return'Movie Master';if(l>=5)return'Rising Critic';return'New Viewer'}
function render(){shell();const l=levelFor(state.xp);$('#cf-level').textContent=l.level;$('#cf-level-mini').textContent=l.level;$('#cf-rank').textContent=rank(l.level);$('#cf-xp-fill').style.width=`${l.percent}%`;$('#cf-xp-current').textContent=`${l.current.toLocaleString()} / ${l.need.toLocaleString()} XP`;$('#cf-xp-next').textContent=`${Math.max(0,l.need-l.current).toLocaleString()} XP to next`;$('#cf-coins').textContent=`${state.coins.toLocaleString()} 🪙`;$('#cf-stat-plays').textContent=state.stats.plays;$('#cf-stat-ratings').textContent=state.stats.ratings;$('#cf-stat-social').textContent=state.stats.social;$('#cf-stat-streak').textContent=`${state.streak} day${state.streak===1?'':'s'}`;$('#cf-ach-count').textContent=`${state.unlocked.length} / ${ACH.length} unlocked`;$('#cf-achievements').innerHTML=ACH.map(a=>`<article class="cf-achievement ${state.unlocked.includes(a.id)?'unlocked':''}"><i>${a.icon}</i><b>${a.name}</b><span>${a.desc}</span></article>`).join('')}
function open(){render();$('#cf-progress-shell').classList.add('open');document.body.style.overflow='hidden'}function close(){$('#cf-progress-shell')?.classList.remove('open');document.body.style.overflow=''}
function once(key,fn){const k=`cf34_${key}`;if(sessionStorage.getItem(k))return;sessionStorage.setItem(k,'1');fn()}
function hook(){if(typeof window.startPlayback==='function'&&!window.startPlayback.__cf34){const old=window.startPlayback;window.startPlayback=function(){const item=window.currentItem||{};const id=item.id||'unknown';const day=today();once(`play_${day}_${id}`,()=>stat('plays',1,35,'Title started',5));return old.apply(this,arguments)};window.startPlayback.__cf34=true}
if(typeof window.cfPostComment==='function'&&!window.cfPostComment.__cf34){const old=window.cfPostComment;window.cfPostComment=async function(){const before=$('#cf-comment-input')?.value?.trim();const r=await old.apply(this,arguments);if(before)stat('social',1,18,'Community comment',2);return r};window.cfPostComment.__cf34=true}
if(typeof window.cfRateTitle==='function'&&!window.cfRateTitle.__cf34){const old=window.cfRateTitle;window.cfRateTitle=function(){stat('ratings',1,15,'Movie rating',2);return old.apply(this,arguments)};window.cfRateTitle.__cf34=true}
if(window.CineFlexParty&&!window.CineFlexParty.__cf34){const oldCreate=window.CineFlexParty.createRoom;window.CineFlexParty.createRoom=async function(){const r=await oldCreate.apply(this,arguments);stat('parties',1,60,'Watch Party hosted',10);return r};window.CineFlexParty.__cf34=true}}
function init(){load();shell();render();checkAchievements();save();setTimeout(hook,1200);setTimeout(hook,3500);if(window.auth?.onAuthStateChanged)auth.onAuthStateChanged(u=>{if(u){syncCloud().then(daily)}else daily()});else daily();window.addEventListener('storage',e=>{if(e.key==='cineflex_profile'){load();syncCloud();render()}})}
document.addEventListener('DOMContentLoaded',init);window.CineFlexProgress={open,addXP,stat,getState:()=>state};
})();
