(function(){
'use strict';
const CFG=window.CINEFLEX_YOUTUBE||{};
const CACHE='cineflex_kdrama_tagalog_v3';
const QUERIES=['korean drama tagalog dubbed full episode','kdrama tagalog dubbed full episode','korean drama tagalog dub full movie','korean series tagalog dubbed'];
let items=[],visible=[],activeId='',query='',sort='Newest';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ready=()=>CFG.apiKey&&CFG.apiKey!=='YOUR_RESTRICTED_YOUTUBE_API_KEY';
function sec(v){const m=String(v||'').match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);return m?(+m[1]||0)*3600+(+m[2]||0)*60+(+m[3]||0):0}
function fmt(n){n=+n||0;return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(0)+'K':String(n)}
async function api(path,p){const q=new URLSearchParams({...p,key:CFG.apiKey});const r=await fetch('https://www.googleapis.com/youtube/v3/'+path+'?'+q);if(!r.ok){let d='';try{d=(await r.json())?.error?.message||''}catch(_){}throw Error(d||'YouTube API error '+r.status)}return r.json()}
async function load(){const found=new Map();for(const term of QUERIES){let token='';for(let page=0;page<2;page++){const p={part:'snippet',type:'video',videoEmbeddable:'true',safeSearch:'moderate',maxResults:'50',q:term,relevanceLanguage:'tl',regionCode:'PH',order:page?'date':'relevance'};if(token)p.pageToken=token;const d=await api('search',p);(d.items||[]).forEach(x=>{const id=x.id?.videoId;if(id)found.set(id,{id,title:x.snippet?.title||'',description:x.snippet?.description||'',thumbnail:x.snippet?.thumbnails?.high?.url||x.snippet?.thumbnails?.medium?.url||'',channelTitle:x.snippet?.channelTitle||'',publishedAt:x.snippet?.publishedAt||''})});token=d.nextPageToken||'';if(!token)break}}
const ids=[...found.keys()],out=[];for(let i=0;i<ids.length;i+=50){const d=await api('videos',{part:'contentDetails,status,statistics,snippet',id:ids.slice(i,i+50).join(',')});for(const v of d.items||[]){const t=(v.snippet?.title||'').toLowerCase(),desc=(v.snippet?.description||'').toLowerCase(),duration=sec(v.contentDetails?.duration);if(v.status?.privacyStatus!=='public'||v.status?.embeddable!==true||duration<1080)continue;if(/trailer|teaser|shorts?|reaction|review|recap|behind the scenes|music video/.test(t))continue;if(!(/tagalog|filipino|pinoy/.test(t+' '+desc)&&/korean|korea|kdrama|k-drama/.test(t+' '+desc)))continue;out.push({id:v.id,title:v.snippet?.title||'',description:v.snippet?.description||'',thumbnail:v.snippet?.thumbnails?.high?.url||'',channelTitle:v.snippet?.channelTitle||'',publishedAt:v.snippet?.publishedAt||'',duration,views:+v.statistics?.viewCount||0})}}
items=[...new Map(out.map(x=>[x.id,x])).values()];localStorage.setItem(CACHE,JSON.stringify({at:Date.now(),items}));return items}
function cached(){try{const c=JSON.parse(localStorage.getItem(CACHE)||'null');if(c&&Date.now()-c.at<6*3600000&&Array.isArray(c.items))return c.items}catch(_){}return null}
function shell(){return `<section id="cfKd" class="cf-kd" aria-hidden="true"><header><div><i class="fa-solid fa-tv"></i><span><b>K-Drama Tagalog Dub</b><small>Available public YouTube episodes and movies</small></span></div><button onclick="cfCloseKDrama()"><i class="fa-solid fa-xmark"></i></button></header><main><div class="cf-kd-tools"><label><i class="fa-solid fa-magnifying-glass"></i><input placeholder="Search title or channel..." oninput="cfKDramaSearch(this.value)"></label><select onchange="cfKDramaSort(this.value)"><option>Newest</option><option>Most Viewed</option><option>Longest</option><option>Title A–Z</option></select><button onclick="cfRefreshKDrama(true)"><i class="fa-solid fa-rotate"></i> Refresh</button></div><div class="cf-kd-title"><h2>Tagalog-Dubbed Korean Drama</h2><span id="cfKdCount">Loading…</span></div><div id="cfKdStatus" class="cf-kd-status"><i class="fa-solid fa-spinner fa-spin"></i> Loading catalog…</div><div id="cfKdGrid" class="cf-kd-grid"></div></main></section><div id="cfKdPlayer" class="cf-kd-player" aria-hidden="true"><div class="cf-kd-card"><div class="cf-kd-top"><button class="cf-kd-back" onclick="cfCloseKDramaPlayer()"><i class="fa-solid fa-arrow-left"></i> Back to Episodes</button><h3 id="cfKdNow">K-Drama</h3><button onclick="cfKDramaFullscreen()"><i class="fa-solid fa-expand"></i></button></div><div id="cfKdScreen" class="cf-kd-screen"><iframe id="cfKdFrame" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe></div><div class="cf-kd-foot"><button onclick="cfKDramaPrev()"><i class="fa-solid fa-backward-step"></i> Previous</button><a id="cfKdYT" target="_blank" rel="noopener"><i class="fa-brands fa-youtube"></i> YouTube</a><button onclick="cfKDramaNext()">Next <i class="fa-solid fa-forward-step"></i></button></div></div></div>`}
function render(){visible=items.filter(x=>!query||(x.title+' '+x.channelTitle).toLowerCase().includes(query));if(sort==='Most Viewed')visible.sort((a,b)=>b.views-a.views);else if(sort==='Longest')visible.sort((a,b)=>b.duration-a.duration);else if(sort==='Title A–Z')visible.sort((a,b)=>a.title.localeCompare(b.title));else visible.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt));document.getElementById('cfKdCount').textContent=visible.length+' available';document.getElementById('cfKdStatus').hidden=true;document.getElementById('cfKdGrid').innerHTML=visible.map(x=>`<article><button onclick="cfPlayKDrama('${x.id}')"><img src="${esc(x.thumbnail)}" loading="lazy" alt=""><i class="fa-solid fa-play"></i></button><h3>${esc(x.title)}</h3><p>${esc(x.channelTitle)} • ${fmt(x.views)} views</p></article>`).join('')||'<div class="cf-kd-empty">No matching videos found.</div>'}
async function refresh(force){const s=document.getElementById('cfKdStatus');s.hidden=false;s.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Loading catalog…';try{if(!ready())throw Error('YouTube API key is not configured.');items=force?await load():(cached()||await load());render()}catch(e){s.innerHTML='<i class="fa-solid fa-triangle-exclamation"></i><b> Catalog could not load</b><p>'+esc(e.message)+'</p>'}}
function init(){if(document.getElementById('cfKd'))return;document.body.insertAdjacentHTML('beforeend',shell())}
function landscape(){const screen=document.getElementById('cfKdScreen');try{screen?.requestFullscreen?.().catch(()=>{})}catch(_){}try{screen?.webkitRequestFullscreen?.()}catch(_){}try{screen?.orientation?.lock?.('landscape')}catch(_){}try{screen?.screen?.orientation?.lock?.('landscape')}catch(_){}try{window.screen?.orientation?.lock?.('landscape')}catch(_){}}
window.cfOpenKDrama=function(){init();const el=document.getElementById('cfKd');el.classList.add('active');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';try{closeMenuDrawer()}catch(_){}if(!items.length)refresh(false)};
window.cfCloseKDrama=function(){cfCloseKDramaPlayer();const el=document.getElementById('cfKd');el?.classList.remove('active');el?.setAttribute('aria-hidden','true');document.body.style.overflow=''};
window.cfRefreshKDrama=refresh;window.cfKDramaSearch=v=>{query=String(v||'').trim().toLowerCase();render()};window.cfKDramaSort=v=>{sort=v;render()};
window.cfPlayKDrama=function(id){const x=items.find(v=>v.id===id);if(!x)return;activeId=id;document.getElementById('cfKdNow').textContent=x.title;document.getElementById('cfKdFrame').src='https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?autoplay=1&rel=0&modestbranding=1&playsinline=0';document.getElementById('cfKdYT').href='https://www.youtube.com/watch?v='+encodeURIComponent(id);const p=document.getElementById('cfKdPlayer');p.classList.add('active');p.setAttribute('aria-hidden','false');history.pushState({cfKdPlayer:true},'');setTimeout(landscape,80)};
window.cfCloseKDramaPlayer=function(){const p=document.getElementById('cfKdPlayer');p?.classList.remove('active');p?.setAttribute('aria-hidden','true');const f=document.getElementById('cfKdFrame');if(f)f.src='';try{if(document.fullscreenElement)document.exitFullscreen()}catch(_){}try{screen.orientation?.unlock?.()}catch(_){}};
window.cfKDramaFullscreen=landscape;window.cfKDramaPrev=function(){const i=visible.findIndex(x=>x.id===activeId);if(i>=0)cfPlayKDrama(visible[(i-1+visible.length)%visible.length].id)};window.cfKDramaNext=function(){const i=visible.findIndex(x=>x.id===activeId);if(i>=0)cfPlayKDrama(visible[(i+1)%visible.length].id)};
window.addEventListener('popstate',()=>{const p=document.getElementById('cfKdPlayer');if(p?.classList.contains('active'))cfCloseKDramaPlayer()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
