(() => {
'use strict';
const $=id=>document.getElementById(id), TMDB_KEY='742aa17a327005b91fb6602054523286', TMDB='https://api.themoviedb.org/3';
let reqs=[],reports=[],imports=[],notices=[];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=v=>{try{return (v?.toDate?v.toDate():new Date(v||Date.now())).toLocaleString()}catch{return '—'}};
const notify=m=>{if(typeof toast==='function')toast(m);else alert(m)};
function ticketHtml(x,kind){const isReq=kind==='request';const title=isReq?(x.title||'Untitled request'):(x.media?.title||x.category||'Reported issue');const note=isReq?(x.notes||`${x.type||'content'} request`):(x.details||x.category||'No details');const opts=isReq?['pending','approved','added','declined']:['pending','checking','fixed','closed'];return `<div class="ticket"><div><h3>${esc(title)}</h3><p>${esc(note)}</p><small>${esc(x.userName||x.userEmail||'User')} · ${dt(x.createdAt)}${!isReq&&x.media?.season?` · S${x.media.season} E${x.media.episode||1}`:''}</small></div><div class="ticket-actions"><span class="status-${esc(x.status||'pending')}">${esc(x.status||'pending')}</span><select data-kind="${kind}" data-id="${x.id}">${opts.map(o=>`<option value="${o}" ${o===(x.status||'pending')?'selected':''}>${o}</option>`).join('')}</select><button data-delete-kind="${kind}" data-id="${x.id}" title="Delete"><i class="fa-solid fa-trash"></i></button></div></div>`}
function renderRequests(){const f=$('requestFilter')?.value||'all';const a=reqs.filter(x=>f==='all'||x.status===f);$('requestManager').innerHTML=a.map(x=>ticketHtml(x,'request')).join('')||'<p class="muted">No requests found.</p>';bindTicketActions()}
function renderReports(){const f=$('reportFilter')?.value||'all';const a=reports.filter(x=>f==='all'||x.status===f);$('reportManager').innerHTML=a.map(x=>ticketHtml(x,'report')).join('')||'<p class="muted">No reports found.</p>';bindTicketActions()}
function bindTicketActions(){document.querySelectorAll('[data-kind]').forEach(s=>s.onchange=async()=>{const col=s.dataset.kind==='request'?'contentRequests':'brokenLinkReports';await db.collection(col).doc(s.dataset.id).update({status:s.value,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});notify('Status updated')});document.querySelectorAll('[data-delete-kind]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this item?'))return;const col=b.dataset.deleteKind==='request'?'contentRequests':'brokenLinkReports';await db.collection(col).doc(b.dataset.id).delete();notify('Item deleted')})}
function renderNotices(){$('notificationManager').innerHTML=notices.map(n=>`<div class="activity"><div><b>${esc(n.title||'Notification')}</b><br><small>${esc(n.message||'')} · ${dt(n.createdAt)}</small></div><button class="ghost-btn" data-toggle-notice="${n.id}">${n.active?'Disable':'Enable'}</button></div>`).join('')||'<p class="muted">No notifications yet.</p>';document.querySelectorAll('[data-toggle-notice]').forEach(b=>b.onclick=async()=>{const n=notices.find(x=>x.id===b.dataset.toggleNotice);await db.collection('cineflexNotifications').doc(n.id).update({active:!n.active,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})})}
function renderImports(){$('importedManager').innerHTML=imports.map(x=>`<div class="activity"><div><b>${esc(x.title||x.name||'Imported title')}</b><br><small>${esc(x.mediaType||'movie')} · TMDB ${esc(x.tmdbId||'')}</small></div><span class="badge">Saved</span></div>`).join('')||'<p class="muted">No imported titles yet.</p>'}
function analytics(){if(!$('analyticsRequests'))return;$('analyticsRequests').textContent=reqs.length;$('analyticsReports').textContent=reports.length;$('analyticsNotifications').textContent=notices.length;$('analyticsImports').textContent=imports.length;const group=(a,key)=>a.reduce((m,x)=>(m[x[key]||'unknown']=(m[x[key]||'unknown']||0)+1,m),{});$('requestBreakdown').innerHTML=Object.entries(group(reqs,'status')).map(([k,v])=>`<div class="progress-row"><span>${esc(k)}</span><b>${v}</b></div>`).join('')||'<p class="muted">No data yet.</p>';$('reportBreakdown').innerHTML=Object.entries(group(reports,'status')).map(([k,v])=>`<div class="progress-row"><span>${esc(k)}</span><b>${v}</b></div>`).join('')||'<p class="muted">No data yet.</p>'}
function start(){db.collection('contentRequests').orderBy('createdAt','desc').limit(100).onSnapshot(s=>{reqs=s.docs.map(d=>({id:d.id,...d.data()}));renderRequests();analytics()});db.collection('brokenLinkReports').orderBy('createdAt','desc').limit(100).onSnapshot(s=>{reports=s.docs.map(d=>({id:d.id,...d.data()}));renderReports();analytics()});db.collection('cineflexNotifications').orderBy('createdAt','desc').limit(30).onSnapshot(s=>{notices=s.docs.map(d=>({id:d.id,...d.data()}));renderNotices();analytics()});db.collection('importedContent').orderBy('importedAt','desc').limit(50).onSnapshot(s=>{imports=s.docs.map(d=>({id:d.id,...d.data()}));renderImports();analytics()});}
$('requestFilter')?.addEventListener('change',renderRequests);$('reportFilter')?.addEventListener('change',renderReports);
$('notificationForm')?.addEventListener('submit',async e=>{e.preventDefault();await db.collection('cineflexNotifications').add({title:$('notificationTitle').value.trim(),message:$('notificationMessage').value.trim(),type:$('notificationType').value,active:$('notificationActive').checked,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:auth.currentUser?.email||''});e.target.reset();$('notificationActive').checked=true;notify('Notification published')});
let fetched=null;
$('fetchTmdb')?.addEventListener('click',async()=>{const type=$('importType').value,id=$('importId').value.trim();if(!id)return notify('Enter a TMDB ID');$('importPreview').innerHTML='<p class="muted">Fetching TMDB data…</p>';try{const r=await fetch(`${TMDB}/${type}/${encodeURIComponent(id)}?api_key=${TMDB_KEY}`);if(!r.ok)throw new Error('TMDB item not found');const x=await r.json();fetched={tmdbId:Number(id),mediaType:type,title:x.title||x.name||'',overview:x.overview||'',posterPath:x.poster_path||'',backdropPath:x.backdrop_path||'',releaseDate:x.release_date||x.first_air_date||'',genres:(x.genres||[]).map(g=>({id:g.id,name:g.name})),voteAverage:x.vote_average||0};$('importPreview').innerHTML=`<div class="import-card"><img src="${x.poster_path?'https://image.tmdb.org/t/p/w342'+x.poster_path:'icon-192.png'}" alt=""><div><h3>${esc(fetched.title)}</h3><p class="muted">${esc(fetched.releaseDate)} · ${esc(fetched.genres.map(g=>g.name).join(', '))}</p><p>${esc(fetched.overview.slice(0,420))}</p><button id="saveImported" class="primary-btn">Save to CineFlex</button></div></div>`;$('saveImported').onclick=async()=>{await db.collection('importedContent').doc(`${type}_${id}`).set({...fetched,importedAt:firebase.firestore.FieldValue.serverTimestamp(),importedBy:auth.currentUser?.email||''},{merge:true});notify('Content imported')};}catch(err){$('importPreview').innerHTML=`<p style="color:var(--danger)">${esc(err.message)}</p>`}});
const wait=setInterval(()=>{if(window.db&&window.auth){clearInterval(wait);auth.onAuthStateChanged(u=>{if(u)start()})}},200);
})();
