const CATS=["Trending","Romance","Billionaire / CEO","Revenge","Contract Marriage","Royal / Empress","Werewolf / Fantasy","Betrayal","Thriller","Completed Series"];
const SOURCES=[{"id": "yt-iqiyi", "channel": "iQIYI Short Drama", "youtube": "https://www.youtube.com/@iQIYIShortDrama", "categories": ["Trending", "Romance", "Billionaire / CEO", "Revenge", "Contract Marriage", "Thriller"]}, {"id": "yt-lakas", "channel": "Lakas Drama PH", "youtube": "https://www.youtube.com/@LakasDramaPH", "categories": ["Romance", "Billionaire / CEO", "Revenge", "Werewolf / Fantasy", "Betrayal"]}, {"id": "yt-tang", "channel": "Tang Global / 柑橘短剧社", "youtube": "https://www.youtube.com/c/TangGlobal", "categories": ["Trending", "Romance", "Billionaire / CEO", "Revenge", "Contract Marriage", "Werewolf / Fantasy"]}, {"id": "yt-anik", "channel": "Anik Sahan", "youtube": "https://www.youtube.com/channel/UCBClWnw8wYBJpzfpUvKYZcQ", "categories": ["Romance", "Betrayal", "Thriller"]}];
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[m]));}
function icon(c){return {"Trending":"🔥","Romance":"❤️","Billionaire / CEO":"💰","Revenge":"💔","Contract Marriage":"💍","Royal / Empress":"👑","Werewolf / Fantasy":"🐺","Betrayal":"😭","Thriller":"🔥","Completed Series":"✨"}[c]||"🎬";}
function card(s,cat){let d=document.createElement("article");d.className="card";d.innerHTML='<div class="poster"><b>'+esc(s.channel)+'</b><small>Official YouTube source</small></div>';d.onclick=()=>window.open(s.youtube,"_blank","noopener");return d;}
function render(){let rows=document.getElementById("rows");rows.innerHTML="";CATS.forEach(cat=>{let arr=SOURCES.filter(s=>s.categories.includes(cat));let sec=document.createElement("section");sec.className="row";sec.innerHTML="<h2>"+icon(cat)+" "+esc(cat)+"</h2><div class='cards'></div>";let box=sec.querySelector(".cards");if(!arr.length)box.innerHTML="<div class='empty'>More official sources coming soon.</div>";else arr.forEach(s=>box.appendChild(card(s,cat)));rows.appendChild(sec);});}
render();document.getElementById("browseBtn").onclick=()=>document.querySelector(".row")?.scrollIntoView({behavior:"smooth"});
const modal=document.getElementById("searchModal"),input=document.getElementById("searchInput"),results=document.getElementById("searchResults");
document.getElementById("searchBtn").onclick=()=>{modal.hidden=false;input.focus()};document.getElementById("closeSearch").onclick=()=>modal.hidden=true;
input.oninput=()=>{let q=input.value.toLowerCase();results.innerHTML=SOURCES.filter(s=>(s.channel+" "+s.categories.join(" ")).toLowerCase().includes(q)).map(s=>"<div class='result'><b>"+esc(s.channel)+"</b><br><small>"+esc(s.categories.join(" • "))+"</small></div>").join("")||"<div class='empty'>No results.</div>";};