'use strict';
const API_KEY='742aa17a327005b91fb6602054523286',BASE='https://api.themoviedb.org/3',IMG='https://image.tmdb.org/t/p/w500';
let page=1,loading=false,done=false,items=[],companyIds=[];
const grid=document.getElementById('grid'),statusEl=document.getElementById('status'),search=document.getElementById('search');
async function j(url){const r=await fetch(url);if(!r.ok)throw new Error(r.status);return r.json()}
async function resolveCompanies(){
  const names=['Vivamax','Viva Films','Viva Communications'];
  const sets=await Promise.all(names.map(n=>j(`${BASE}/search/company?api_key=${API_KEY}&query=${encodeURIComponent(n)}`).catch(()=>({results:[]}))));
  companyIds=[...new Set(sets.flatMap(x=>x.results||[]).filter(x=>/viva/i.test(x.name||'')).map(x=>x.id))];
}
function openItem(x){location.href=`details.html?id=${x.id}&type=${x.media_type||'movie'}&title=${encodeURIComponent(x.title||x.name||'CineFlex')}`}
function render(list,append=true){if(!append)grid.innerHTML=''; const frag=document.createDocumentFragment();list.forEach(x=>{if(!x.poster_path)return;const c=document.createElement('article');c.className='card';c.tabIndex=0;c.dataset.id=x.id;c.innerHTML=`<img loading="lazy" src="${IMG+x.poster_path}" alt=""><div class="name">${escapeHtml(x.title||x.name||'Untitled')}</div>`;c.onclick=()=>openItem(x);c.onkeydown=e=>{if(e.key==='Enter')openItem(x)};frag.appendChild(c)});grid.appendChild(frag);items=append?items.concat(list):list;statusEl.textContent=`${grid.children.length} Vivamax titles loaded`;}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadMore(){if(loading||done)return;loading=true;statusEl.textContent='Loading Vivamax movies…';try{if(!companyIds.length)await resolveCompanies();let results=[];if(companyIds.length){const calls=companyIds.slice(0,5).map(id=>j(`${BASE}/discover/movie?api_key=${API_KEY}&with_companies=${id}&sort_by=popularity.desc&page=${page}`).catch(()=>({results:[]})));results=(await Promise.all(calls)).flatMap(x=>x.results||[]);}if(!results.length){const f=await j(`${BASE}/discover/movie?api_key=${API_KEY}&region=PH&with_origin_country=PH&sort_by=popularity.desc&page=${page}`);results=f.results||[];}const seen=new Set(items.map(x=>x.id));results=results.filter(x=>!seen.has(x.id));render(results,true);page++;if(!results.length)done=true;}catch(e){statusEl.textContent='Could not load titles. Check your connection.'}finally{loading=false}}
search.addEventListener('input',async()=>{const q=search.value.trim();if(!q){grid.innerHTML='';items=[];page=1;done=false;loadMore();return}if(q.length<2)return;statusEl.textContent='Searching…';try{const d=await j(`${BASE}/search/movie?api_key=${API_KEY}&query=${encodeURIComponent(q)}&region=PH`);render((d.results||[]).filter(x=>x.poster_path),false)}catch(e){}});
document.getElementById('loadMore').onclick=loadMore;
window.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter','Escape','Backspace'].includes(e.key))return;if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;const cards=[...grid.querySelectorAll('.card')];if(!cards.length)return;let i=cards.indexOf(document.activeElement);if(i<0)i=0;const cols=Math.max(1,Math.round(grid.clientWidth/cards[0].getBoundingClientRect().width));if(e.key==='ArrowRight')i=Math.min(cards.length-1,i+1);if(e.key==='ArrowLeft')i=Math.max(0,i-1);if(e.key==='ArrowDown')i=Math.min(cards.length-1,i+cols);if(e.key==='ArrowUp')i=Math.max(0,i-cols);if(e.key==='Enter')cards[i].click();if(e.key==='Escape'||e.key==='Backspace'){history.back();return}e.preventDefault();cards[i].focus({preventScroll:true});cards[i].scrollIntoView({block:'center',inline:'center',behavior:'smooth'});});
loadMore();
